name: CI - Build and Push to ECR

on:
  push:
    branches: [ main ]

  workflow_dispatch:


concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: threatmod-ecr

jobs:
  build-and-push:
    name: Build, Scan and Push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Build
        run: |
          docker build -t ${{ env.ECR_REPOSITORY }}:${{ github.sha }} app/

      - name: Scan image with Grype
        uses: anchore/scan-action@v6
        with:
          image: "${{ env.ECR_REPOSITORY }}:${{ github.sha }}"
          fail-build: "true"
          severity-cutoff: high
          output-format: table

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        run: |
          docker tag ${{ env.ECR_REPOSITORY }}:${{ github.sha }} \
            $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

          docker tag ${{ env.ECR_REPOSITORY }}:${{ github.sha }} \
            $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest

          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest

          echo "### Image pushed :white_check_mark:" >> $GITHUB_STEP_SUMMARY
          echo "**Image:** \`$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY